weights: tph-yolov5-main/tph-yolov5-main
cfg: /root/autodl-tmp/tph-yolov5-main/tph-yolov5-main/models/yolov5l-xs-tph.yaml
data: /root/autodl-tmp/ultralytics/cfg/datasets/DOTA.yaml
hyp: tph-yolov5-main/tph-yolov5-main/data/hyps/hyp.scratch.yaml
epochs: 200
batch_size: 16
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 20
project: tph-yolov5-main/tph-yolov5-main/runs/train
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: tph-yolov5-main/tph-yolov5-main/runs/train/exp13
